### ISSUE TITLE
the tomcat container return 143 after the command of the docker stop

### ISSUE THREAD

**Issue by zhangguanzhang** [docker-library/tomcat#146] opened 2019-02-19 05:22 UTC
```
[vagrant@vagrant-kubernetes ~]$ docker run -dit --name tomcat -p 8080:8080 tomcat
Digest: sha256:f83f353d1f631ce202a398334ea4368b07768f33804b820fe51838a90e7e2c58
[vagrant@vagrant-kubernetes ~]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS                    NAMES
91c01eccfdda        tomcat              "catalina.sh run"   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp   tomcat
[vagrant@vagrant-kubernetes ~]$ docker stop tomcat
tomcat
[vagrant@vagrant-kubernetes ~]$ docker ps -a|grep tomcat
91c01eccfdda        tomcat               "catalina.sh run"        About a minute ago   Exited (143) 7 seconds ago                       tomcat
```

**Comment by wglambert** [comment] 2019-02-19 17:32
That's the exit code for a `SIGTERM` https://docs.docker.com/engine/reference/commandline/stop/
>The main process inside the container will receive `SIGTERM`, and after a grace period, `SIGKILL`.

An exit code of 128+ is a signal. Where the signal's value is the difference between the exit code minus 128.

```console
$ man 7 signal
. . .
       SIGHUP        1       Term    Hangup detected on controlling terminal
                                     or death of controlling process
       SIGINT        2       Term    Interrupt from keyboard
       SIGQUIT       3       Core    Quit from keyboard
       SIGILL        4       Core    Illegal Instruction
       SIGABRT       6       Core    Abort signal from abort(3)
       SIGFPE        8       Core    Floating-point exception
       SIGKILL       9       Term    Kill signal
       SIGSEGV      11       Core    Invalid memory reference
       SIGPIPE      13       Term    Broken pipe: write to pipe with no
                                     readers; see pipe(7)
       SIGALRM      14       Term    Timer signal from alarm(2)
       SIGTERM      15       Term    Termination signal
```

See also http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by wglambert** [comment] 2019-02-20 21:23
Closing since the question is sufficiently answered,

I would also consider this a duplicate of https://github.com/docker-library/tomcat/issues/57

**Closed by wglambert** 2019-02-20 21:23 UTC
Labels: question
