### ISSUE TITLE
Run as different user

### ISSUE THREAD

**Issue by jdesmet** [docker-library/tomcat#118] opened 2018-04-23 05:18 UTC
Tomcat should be extracted using  `umask 022`. This will allow users to run tomcat as a different user, maybe multiple different users each with their own `CATALINA_BASE`.

**Comment by tianon** [comment] 2018-04-23 20:35
Duplicate of https://github.com/docker-library/tomcat/issues/68 and https://github.com/docker-library/tomcat/issues/35.

Does simply setting `umask` actually do the trick?  Does upstream have any docs that would make it more clear we need to do this (because we didn't need to in the past), or do we have to link to our own issues about it instead?

(Closing since this is a duplicate, but I'm going to cross-post your comment over to #35.)

**Closed by tianon** 2018-04-23 20:35 UTC
