### ISSUE TITLE
Container using 9-jre8-alpine fails

### ISSUE THREAD

**Issue by esantiagovieira** [docker-library/tomcat#149] opened 2019-03-25 20:12 UTC
When trying to run the image above, I am getting the below error:

```
ERROR: unsatisfiable constraints:
  openjdk8-8.201.08-r0:
    breaks: .native-build-deps-0[openjdk8=8.191.12-r0]
ERROR: Service 'unoerp' failed to build: The command '/bin/sh -c set -eux; 		apk add --no-cache --virtual .fetch-deps 		gnupg 		ca-certificates 		openssl 	; 		export GNUPGHOME="$(mktemp -d)"; 	for key in $GPG_KEYS; do 		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; 	done; 		success=; 	for url in $TOMCAT_TGZ_URLS; do 		if wget -O tomcat.tar.gz "$url"; then 			success=1; 			break; 		fi; 	done; 	[ -n "$success" ]; 		echo "$TOMCAT_SHA512 *tomcat.tar.gz" | sha512sum -c -; 		success=; 	for url in $TOMCAT_ASC_URLS; do 		if wget -O tomcat.tar.gz.asc "$url"; then 	success=1; 			break; 		fi; 	done; 	[ -n "$success" ]; 		gpg --batch --verify tomcat.tar.gz.asc tomcat.tar.gz; 	tar -xvf tomcat.tar.gz --strip-components=1; 	rm bin/*.bat; 	rm tomcat.tar.gz*; 	command -v gpgconf && gpgconf --kill all || :; 	rm -rf "$GNUPGHOME"; 		nativeBuildDir="$(mktemp -d)"; 	tar -xvf bin/tomcat-native.tar.gz -C "$nativeBuildDir" --strip-components=1; 	apk add --no-cache --virtual .native-build-deps 		apr-dev 		coreutils 		dpkg-dev dpkg 		gcc 		libc-dev 		make 		"openjdk${JAVA_VERSION%%[-~bu]*}"="8.191.12-r0" 		openssl-dev 	; 	( 		export CATALINA_HOME="$PWD"; 		cd "$nativeBuildDir/native"; gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; 		./configure 			--build="$gnuArch" 			--libdir="$TOMCAT_NATIVE_LIBDIR" 			--prefix="$CATALINA_HOME" 			--with-apr="$(which apr-1-config)" 			--with-java-home="$(docker-java-home)" 			--with-ssl=yes; 		make -j "$(nproc)"; 		make install; 	); 	rm -rf "$nativeBuildDir"; 	rm bin/tomcat-native.tar.gz; 		runDeps="$( 		scanelf --needed --nobanner --format '%n#p' --recursive "$TOMCAT_NATIVE_LIBDIR" 	| tr ',' '\n' 			| sort -u 			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' 	)"; 	apk add --virtual .tomcat-native-rundeps $runDeps; 	apk del .fetch-deps .native-build-deps; 		apk add --no-cache bash; 	find ./bin/ -name '*.sh' -exec sed -ri 's|^#!/bin/sh$|#!/usr/bin/env bash|' '{}' +; 		chmod -R +rX .; 	chmod 777 logs work' returned a non-zero code: 2
```

It seems that it is caused by the issue reported here https://github.com/gliderlabs/docker-alpine/issues/504#issue-422856137.

Nonetheless, I am unsure if that is really the root cause. I'd like to know if other people are encountering the same issue.

For the moment, I managed to workaround the problem changing line 85 of the Docker file to match the expected JAVA_VERSION
`"openjdk${JAVA_VERSION%%[-~bu]*}"="8.201.08-r0" \`

No need to say this is wrong and I have no idea on the impact it may cause, but until I find a solution, or assuming this is related to the error from the link above, a bugfix deployed, that's how I managed to get things running for the moment.

**Comment by wglambert** [comment] 2019-03-25 21:21
Essentially a duplicate of https://github.com/docker-library/openjdk/issues/289
The upstream bug report on the issue https://bugs.alpinelinux.org/issues/10126; the latest OpenJDK on Alpine is unintentionally removing `nss`.
The workaround is to just manually re-add nss after getting the latest OpenJDK

**Comment by esantiagovieira** [comment] 2019-03-25 21:51
Honestly, I am no expert, I tried to add workaround as suggest, it ran without errors, but seems it didn't work as expected:

```
Step 14/25 : RUN apk add --no-cache nss
 ---> Using cache
 ---> 77bf9f5e8ef6
Step 15/25 : RUN set -eux;
```
In the end, I will get the same error related to java version mismatch. The weird is that the command reports "Using cache", even though the parameter says to not using, maybe that's the problem? What am I doing wrong? I have added that to line 35 of the Dockerfile.

**Comment by tianon** [comment] 2019-04-04 21:58
This looks like you're trying to _build_ our `Dockerfile`, not just run the image we provide (which is probably what you really ought to be doing instead).

Regardless, the `openjdk` issue referenced above should be fixed *and* the `openjdk` version in the official image should already be bumped.

**Closed by tianon** 2019-04-04 21:58 UTC
Labels: question
