### ISSUE TITLE
Do we have any plans to make tomcat 9 with open JDK 11 alpine?

### ISSUE THREAD

**Issue by arvasrikanth** [docker-library/tomcat#156] opened 2019-05-10 12:18 UTC
Right now tomcat 9 with jre8-alpine is available. Are there any plans to make tomcat9 image with open JDK -11 alpine. If not please post the the reasons

**Comment by wglambert** [comment] 2019-05-10 16:07
There isn't an openjdk:11-alpine https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580

**Comment by wglambert** [comment] 2019-05-10 17:12
Also a duplicate of https://github.com/docker-library/openjdk/issues/313 and https://github.com/docker-library/openjdk/issues/211#issuecomment-438173628

**Closed by wglambert** 2019-05-10 17:12 UTC
Labels: Request

**Comment by DragD** [comment] 2019-10-07 13:47
There is an openjdk11 for Alpine already:
https://pkgs.alpinelinux.org/packages?name=openjdk11&branch=edge
