### ISSUE TITLE
AdoptOpenJDK variant support

### ISSUE THREAD

**Issue by gpuliyar83** [docker-library/tomcat#154] opened 2019-04-25 15:51 UTC
Can you provide the AdoptOpenJDK variant?

**Comment by tianon** [comment] 2019-04-25 20:59
Duplicate of https://github.com/docker-library/tomcat/issues/134.

Would require official images of AdoptOpenJDK as a prerequisite (https://github.com/docker-library/official-images/pull/5710).

**Closed by tianon** 2019-04-25 20:59 UTC
Labels: Request
