### ISSUE TITLE
Container hangs after first start

### ISSUE THREAD

**Issue by hangstl** [docker-library/tomcat#93] opened 2017-11-30 14:51 UTC
I can only start a Tomcat container once. When I do the same command a second time it hangs:

This is what I do:
(1) Start it with: "docker run -it --rm -p 8888:8080 tomcat:8.5.23-jre8"

(2) Check it with "curl localhost:8888" -> everything OK.

(3) Stop the Container with ctrl-c

(4) Start the container again with "docker run -it --rm -p 8888:8080 tomcat:8.5.23-jre8"

(5) Check it with "curl localhost:8888" -> hangs forever.

Last line in logfile is:
30-Nov-2017 15:**45:16**.813 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]

_Update:_ Tomcat does not hang forever, but takes a very long time to finish starting up (> 2 minutes):

30-Nov-2017 15:**47:22**.601 WARNING [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [125,152] milliseconds.
30-Nov-2017 15:47:22.658 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [125,845] ms
30-Nov-2017 15:47:22.659 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
30-Nov-2017 15:47:22.685 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [25] ms
30-Nov-2017 15:47:22.685 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
30-Nov-2017 15:47:22.727 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [42] ms
30-Nov-2017 15:47:22.727 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
30-Nov-2017 15:47:22.756 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [29] ms
30-Nov-2017 15:47:22.756 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
30-Nov-2017 15:47:22.786 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [30] ms
30-Nov-2017 15:47:22.792 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
30-Nov-2017 15:47:22.820 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
30-Nov-2017 15:47:22.839 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 126086 ms

# docker version
Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by yosifkit** [comment] 2017-12-01 00:48
Are you on a VM of a cloud provider? Then it sounds like a duplicate of #12.

**Comment by hangstl** [comment] 2017-12-01 09:01
Problem is when running it in Google Cloud.

On my local Ubuntu VM it works.

In Google Cloud it does not work for Ubuntu 16.04 and 17.04, But works for Debian.

**Comment by hangstl** [comment] 2017-12-01 09:24
I tried --device /dev/urandom:/dev/random (as suggested in #12) - but this doesn't solve the issue, it only relocates it. Now I have to create the entropy on the host system to make Tomcat start.

**Comment by qedrakmar** [comment] 2017-12-01 22:03
Thanks for the heads up.  Please close this issue, if your problem is solved.  Thanks!

**Comment by qedrakmar** [comment] 2017-12-11 19:52
I'm going to go ahead and close this, since it appears both resolved and entropy-related.

**Closed** 2017-12-11 19:53 UTC
