### ISSUE TITLE
Tomcat Image With Manager

### ISSUE THREAD

**Issue by leer5** [docker-library/tomcat#217] opened 2020-11-24 05:44 UTC
I'm not interested in bare bones image to which I add a web app to produce a docker image. I would a tomcat image with the manager app so that I can run it in docker and have access to the manager UI. I plan to deploy SoapUI mock servers as war files to the tomcat container via the UI.  I tried looking the newer images and they all do not have webapps/manager.  I found one tomcat image (tomcat:8 or something like that) which does include webapps/manager but it failed to run my SoapUI war file apparently that image uses java 7.

Any ideas?

**Comment by tianon** [comment] 2020-11-24 19:29
It sounds like this is probably a duplicate of https://github.com/docker-library/tomcat/issues/183, in which case you'll probably be interested in #181 / #124.

**Closed** 2020-12-08 20:38 UTC
