### ISSUE TITLE
docker tomcat:8-slim has examples

### ISSUE THREAD

**Issue by f1-outsourcing** [docker-library/tomcat#167] opened 2019-07-12 11:05 UTC
I am just testing the the docker image tomcat:8-slim this still has the examples. I guess these should to be removed not?

**Comment by tianon** [comment] 2019-07-12 22:20
Duplicate of #124

**Closed by tianon** 2019-07-12 22:20 UTC

**Comment by ondrj** [comment] 2020-01-03 17:36
@f1-outsourcing Can you share the link to the image on Docker Hub, please? Cannot find the image with this name.
