### ISSUE TITLE
Permission problem while running tomcat as a non-root user

### ISSUE THREAD

**Issue by michaljrk** [docker-library/tomcat#35] opened 2016-07-05 08:51 UTC
I'm facing a permission denied issue while trying running _tomcat:9.0.0.M8-jre8_ container as a _www-data_ user. Here is the Dockerfile that I'm using:

```
FROM tomcat:9.0.0.M8-jre8

COPY /conf /usr/local/tomcat/conf

RUN chown -R www-data /usr/local/tomcat

USER www-data

CMD ["catalina.sh", "run"]
```

After starting the container, I'm getting: 

**`bash: /usr/local/tomcat/bin/catalina.sh: Permission denied`**

The files and directories permissions look fine (event if I change to 777 for every directory and files , the problem still occures, I cannot even list _/usr/local/tomcat/bin_ directory as a _www-data_....). I've checked and it **does not** look like SELinux context problem. 

btw. for _8.0.32-jre8_  I'm using the same Dockerfile (with different _FROM_ of course) and it's working fine..

**My environment details:**

docker version:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Host machine (VM):
`
Description:    Ubuntu 14.04.4 LTS, 3.13.0-86-generic`

Any help would be more than appreciated.

**Comment by andyshinn** [comment] 2016-08-04 20:33
Did you ever figure this out? I'm trying to do the same thing and can't figure out what is going on. Permissions appear correct for the user running the container.

**Comment by yosifkit** [comment] 2016-08-04 20:48
It looks like they tightened the permissions in the tar file that is downloaded from apache, since the only difference in their Dockerfiles is the tomcat version.  Maybe we should `chmod +r` all the files and `+x` the folders and executables?

```console
$ docker run -it --rm tomcat:9.0.0-jre8 bash
root@70cfd8c03f7f:/usr/local/tomcat# ls -l
total 120
-rw-r----- 1 root root  57092 Jul  4 18:25 LICENSE
-rw-r----- 1 root root   1804 Jul  4 18:25 NOTICE
-rw-r----- 1 root root   6708 Jul  4 18:25 RELEASE-NOTES
-rw-r----- 1 root root  15946 Jul  4 18:25 RUNNING.txt
drwxr-x--- 2 root root   4096 Jul 29 09:47 bin
drwx--S--- 2 root root   4096 Jul  4 18:25 conf
drwxr-sr-x 3 root staff  4096 Jul 29 09:46 include
drwxr-x--- 2 root root   4096 Jul 29 09:45 lib
drwxr-x--- 2 root root   4096 Jul  4 18:22 logs
drwxr-sr-x 3 root staff  4096 Jul 29 09:46 native-jni-lib
drwxr-x--- 2 root root   4096 Jul 29 09:45 temp
drwxr-x--- 7 root root   4096 Jul  4 18:23 webapps
drwxr-x--- 2 root root   4096 Jul  4 18:22 work


$ docker run -it --rm tomcat:8.0-jre8 bash
root@7dbb88ef837e:/usr/local/tomcat# ls -l
total 120
-rw-r--r-- 1 root root  57011 Jun  9 13:58 LICENSE
-rw-r--r-- 1 root root   1444 Jun  9 13:58 NOTICE
-rw-r--r-- 1 root root   6739 Jun  9 13:58 RELEASE-NOTES
-rw-r--r-- 1 root root  16195 Jun  9 13:58 RUNNING.txt
drwxr-xr-x 2 root root   4096 Jul 29 09:43 bin
drwxr-xr-x 2 root root   4096 Jun  9 13:58 conf
drwxr-sr-x 3 root staff  4096 Jul 29 09:42 include
drwxr-xr-x 2 root root   4096 Jul 29 09:41 lib
drwxr-xr-x 2 root root   4096 Jun  9 13:55 logs
drwxr-sr-x 3 root staff  4096 Jul 29 09:42 native-jni-lib
drwxr-xr-x 2 root root   4096 Jul 29 09:41 temp
drwxr-xr-x 7 root root   4096 Jun  9 13:56 webapps
drwxr-xr-x 2 root root   4096 Jun  9 13:55 work
```

**Comment by michaljrk** [comment] 2016-08-04 20:54
Hey @yosifkit  

> Maybe we should chmod +r all the files and +x the folders and executables?

You may give a try if you want, but I've tried that (set 777 for all files and directories) and it didn't help.. 
It is a little bit mind blowing to be honest.

**Comment by andyshinn** [comment] 2016-08-04 20:55
It looks like this is going to be more complicated that I originally anticipated. After digging in more it is permissions on the script and also folders (such as logging). I've passed the script part but now getting an error trying to write logs (even though the folder is 777, just as @michaljrk mentions).

**Comment by andyshinn** [comment] 2016-08-04 21:57
Through a combination of creating the user inside the image, chowning `/usr/local/tomcat` recursively, and running the container as the same UID on the host, I got this working as intended. It would seem like the entrypoint would need to do a bunch of things to make this seamless without an intermediate image. But maybe just documenting the steps to do this in an intermediate build is enough.

FWIW, after I chowned the entire `/usr/local/tomcat` folder, I didn't need any permissions bits on the `catalina.sh` script. I'm just doing this in my intermediate image:

```
groupadd -r myuser -g 501
useradd -d /home/myuser -u 501 -m -s /bin/bash -g myuser myuser
chown -R myuser:myuser /usr/local/tomcat
```

**Comment by Rillke** [comment] 2016-08-05 16:15
I am facing into the issue mentioned at http://unix.stackexchange.com/q/292729/177226

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```
Host is an Ubuntu Xenial.

When I delete and recreate the directories created by the make script of tomcat9 with exactly the same file permission, the issue is gone. However, this is just an ugly hack and I'd like to understand the underlying issue.

**Comment by Rillke** [comment] 2016-08-05 17:29
Minimal Docker file to illustrate the issue:

```
FROM tomcat:9.0-jre8

ENV RUN_USER            tomcat
ENV RUN_GROUP           tomcat

# Add a tomcat user
RUN groupadd -r ${RUN_GROUP} && useradd -g ${RUN_GROUP} -d ${CATALINA_HOME} -s /bin/bash ${RUN_USER}
RUN chown -R tomcat:tomcat $CATALINA_HOME
RUN ls -lah $CATALINA_HOME
RUN su -c 'touch $CATALINA_HOME/include/this.still.works' tomcat
RUN su -c 'touch $CATALINA_HOME/work/this.will.fail' tomcat
```

Output during `docker build .`:

```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM tomcat:9.0-jre8
 ---> cb71de5ad0b3
Step 2 : ENV RUN_USER tomcat
 ---> Using cache
 ---> ca4ed6c3d872
Step 3 : ENV RUN_GROUP tomcat
 ---> Using cache
 ---> 45d08197205d
Step 4 : RUN groupadd -r ${RUN_GROUP} && useradd -g ${RUN_GROUP} -d ${CATALINA_HOME} -s /bin/bash ${RUN_USER}
 ---> Using cache
 ---> 20322c84ec33
Step 5 : RUN chown -R tomcat:tomcat $CATALINA_HOME
 ---> Using cache
 ---> 30e6ba23e1b4
Step 6 : RUN ls -lah $CATALINA_HOME
 ---> Using cache
 ---> 1d563c4abc37
Step 7 : RUN su -c 'touch $CATALINA_HOME/include/this.still.works' tomcat
 ---> Running in 074318cf0dbb
 ---> 937237fd60f8
Removing intermediate container 074318cf0dbb
Step 8 : RUN su -c 'touch $CATALINA_HOME/work/this.will.fail' tomcat
 ---> Running in dc961fac0610
touch: cannot touch ‘/usr/local/tomcat/work/this.will.fail’: Permission denied
The command '/bin/sh -c su -c 'touch $CATALINA_HOME/work/this.will.fail' tomcat' returned a non-zero code: 1
```

**Comment by yosifkit** [comment] 2016-08-05 18:07
@Rillke, unfortunately I cannot reproduce with your Dockerfile example.  Maybe try deleting the image for tomcat and pulling it again?  My digest from pulling is below.
```console
$ docker pull tomcat:9.0-jre8
...
Digest: sha256:2a6851bbadd7e481680a44da4e50cfed5fd28d1ad6034dcee93b1e3bef3fb145
Status: Downloaded newer image for tomcat:9.0-jre8
$ docker build - <<'EOS'
FROM tomcat:9.0-jre8

ENV RUN_USER            tomcat
ENV RUN_GROUP           tomcat

# Add a tomcat user
RUN groupadd -r ${RUN_GROUP} && useradd -g ${RUN_GROUP} -d ${CATALINA_HOME} -s /bin/bash ${RUN_USER}
RUN chown -R tomcat:tomcat $CATALINA_HOME
RUN ls -lah $CATALINA_HOME
RUN su -c 'touch $CATALINA_HOME/include/this.still.works' tomcat
RUN su -c 'touch $CATALINA_HOME/work/this.will.fail' tomcat
EOS

Sending build context to Docker daemon 2.048 kB
Step 1 : FROM tomcat:9.0-jre8
 ---> cb71ac4603ec
Step 2 : ENV RUN_USER tomcat
 ---> Running in eea76eb77bb9
 ---> 9f0cfba51e84
Removing intermediate container eea76eb77bb9
Step 3 : ENV RUN_GROUP tomcat
 ---> Running in a26f74099a32
 ---> 3c38225280ee
Removing intermediate container a26f74099a32
Step 4 : RUN groupadd -r ${RUN_GROUP} && useradd -g ${RUN_GROUP} -d ${CATALINA_HOME} -s /bin/bash ${RUN_USER}
 ---> Running in be9d5e413be0
 ---> 8d8f353c75ec
Removing intermediate container be9d5e413be0
Step 5 : RUN chown -R tomcat:tomcat $CATALINA_HOME
 ---> Running in c4b81d097e25
 ---> 26e38f516d6f
Removing intermediate container c4b81d097e25
Step 6 : RUN ls -lah $CATALINA_HOME
 ---> Running in f80bca10fd3e
total 128K
drwxr-sr-x 11 tomcat tomcat 4.0K Aug  5 17:35 .
drwxrwsr-x 11 root   staff  4.0K Aug  5 17:35 ..
-rw-r-----  1 tomcat tomcat  56K Jul  4 18:25 LICENSE
-rw-r-----  1 tomcat tomcat 1.8K Jul  4 18:25 NOTICE
-rw-r-----  1 tomcat tomcat 6.6K Jul  4 18:25 RELEASE-NOTES
-rw-r-----  1 tomcat tomcat  16K Jul  4 18:25 RUNNING.txt
drwxr-x---  2 tomcat tomcat 4.0K Aug  5 17:35 bin
drwx--S---  2 tomcat tomcat 4.0K Aug  5 17:35 conf
drwxr-sr-x  3 tomcat tomcat 4.0K Aug  5 17:35 include
drwxr-x---  2 tomcat tomcat 4.0K Aug  5 17:35 lib
drwxr-x---  2 tomcat tomcat 4.0K Jul  4 18:22 logs
drwxr-sr-x  3 tomcat tomcat 4.0K Aug  5 17:35 native-jni-lib
drwxr-x---  2 tomcat tomcat 4.0K Aug  5 17:35 temp
drwxr-x---  7 tomcat tomcat 4.0K Aug  5 17:35 webapps
drwxr-x---  2 tomcat tomcat 4.0K Jul  4 18:22 work
 ---> 6e93c99819d3
Removing intermediate container f80bca10fd3e
Step 7 : RUN su -c 'touch $CATALINA_HOME/include/this.still.works' tomcat
 ---> Running in 3b18f20a69af
 ---> 69289177b105
Removing intermediate container 3b18f20a69af
Step 8 : RUN su -c 'touch $CATALINA_HOME/work/this.will.fail' tomcat
 ---> Running in 1da864dd3d88
 ---> 2c1244595c55
Removing intermediate container 1da864dd3d88
Successfully built 2c1244595c55
```

Machine info:
```console
$ docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 8740
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.5-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.88 GiB
Name: isengard
ID: UOCM:3F65:5FZC:6H5L:W3HY:34G4:A5XZ:SUOV:S2D4:XQTO:4KGA:6XSE
Docker Root Dir: /mnt/spare/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   b9f10c9
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   b9f10c9
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by Rillke** [comment] 2016-08-06 09:30
@yosifkit Thanks! Looks like aufs related. I learned that [permission restrictions from lower layers apply to upper layers, too](docker/docker/issues/783). Still, I don't get why file creation in `include/` and `work/` behaves differently (as they have similar permission flags) and when building tomcat9 itself with aufs, there are no permission issues reported.

Build with boot2docker and aufs:
![docker-permission-error](https://cloud.githubusercontent.com/assets/2311611/17455960/3d837284-5bc8-11e6-8ef7-2b168de4532b.png)

Docker config (for first build):
![docker-permission-error-config](https://cloud.githubusercontent.com/assets/2311611/17455973/96816dfa-5bc8-11e6-8730-e8bf68494a4e.png)

Build with overlayFS (success!):
![docker-permission-error-overlay-fs](https://cloud.githubusercontent.com/assets/2311611/17455975/a8190a82-5bc8-11e6-819a-2cdcba000490.png)

**Comment by serge-medvedev** [comment] 2016-09-01 12:25
With tomcat:9 I've faced an issue very similar to one @Rillke [described](https://github.com/docker-library/tomcat/issues/35#issuecomment-237911842): non-root user isn't permitted to create files/directories in subfolders of CATALINA_HOME.
But I've also noticed that there is no such issue with tomcat:8.0.36-jre8 image.

**Comment by hakamairi** [comment] 2016-11-11 10:43
Like @Rillke wrote, this is aufs related. (check with "docker info" what's your driver)

There are two solutions:

1. Change the docker's driver to a different one (like devicemapper), although be advised that you will need to do that on all your docker services even those on production (this will create additional driver in your /var/lib/docker and you will have either start service with specific driver or delete the other one).

2. Change the permissions in the same layer - this would actually mean that you need to add your relaxed permissions or chown in the same RUN of the original Dockerfile where tomcat.tar.gz is unpacked.

**Comment by julienchastang** [comment] 2017-08-11 17:48
After chasing many red herrings and tearing my hair out, I have finally arrived here. Thanks to those who have provided insight into this issue. This is a major shortcoming/bug in Docker. I verified that my Docker installation is the latest, further ensuring that no old versions of Docker are responsible by purging the VM of Docker before the fresh Docker installation. The original reported issue is more than four years old at this point (https://github.com/moby/moby/issues/783). Some fundamental Unix principles are being violated if you are clearly the owner of a file/directory (verified through `id`, `stat` `groups`, `cat /etc/passwd`, etc. etc.), further ensuring that selinux, AppArmor are not the culprits. Is @hakamairi’s advice still the best workaround at this point?

**Comment by Rillke** [comment] 2017-08-11 21:10
@julienchastang One reason, [besides](https://sthbrx.github.io/blog/2015/10/30/docker-just-stop-using-aufs/) [others](/chriskuehl/docker-storage-benchmark) why we switched to overlay2 in nearly all our systems. We're using [a little script](https://gist.github.com/Rillke/fce689ec63c3611cea815d1d92dcc5f1) for setting Docker up to use overlay2.

**Comment by julienchastang** [comment] 2017-08-11 22:09
Thanks @Rillke. Any reason I should not use devicemapper (which seems to address this issue after running some tests)?

**Comment by yosifkit** [comment] 2017-08-23 21:00
@julienchastang, if you are still switching to devicemapper, be sure to configure for `direct-lvm` since that will boost performance and reliability significantly: [docs.docker](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production).  Here is Docker's article on choosing which one to use: [docs.docker](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/).

**Comment by gliptak** [comment] 2017-11-17 20:40
I observed permission issues preventing Tomcat from writing logs and coming up, and setting ```selinux``` permissive corrected these.

**Comment by jakefeasel** [comment] 2018-02-27 13:58
I experienced this too, filed here: https://devops.stackexchange.com/questions/3426/permission-errors-with-non-root-user-when-running-on-linux

**Comment by yosifkit** [comment] 2018-02-27 22:52
@jakefeasel, some storage drivers, like aufs, (how image layers are committed to disk) are not able to properly commit a layer that only changes permissions.

**Comment by MadeInChina** [comment] 2018-03-21 04:08
```
FROM tomcat:8.5-jre8-alpine

ENV TIMEZONE 'Europe/Amsterdam'

ENV TOMCAT_MAXTHREADS 150
ENV TOMCAT_MINSPARETHREADS 4

ARG userid=1001
ARG groupid=1001
ARG user=tomcat

ENV LOCAL_USER_ID=$userid
ENV LOCAL_GROUP_ID=$groupid
ENV USER=$user

RUN echo http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
    apk -U upgrade && \
    apk --update add nano && \
    apk --no-cache add tzdata shadow gosu libc6-compat && \
    rm -rf /var/cache/apk/* && \
    cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
    echo ${TIMEZONE} > /etc/timezone && \
    echo ${TIMEZONE} > /etc/TZ && \
    unset TZ

ADD docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 8080
EXPOSE 8009

CMD ["catalina.sh", "run"]
```

docker-entrypoint.sh
```

#!/bin/bash
# Credit goes to https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
# Modified to allow adding groups and mounting volumes as home of the user


# Add local user
# Either use the LOCAL_USER_ID if passed in at runtime or
# fallback

USER_ID=${LOCAL_USER_ID:-9001}

echo "Starting with UID : $USER_ID"
groupadd -r $USER -g $LOCAL_GROUP_ID
useradd --shell /bin/bash -u $USER_ID -g $LOCAL_GROUP_ID -o -c "" -m $USER

chown -R $USER_ID:$LOCAL_GROUP_ID /usr/local/tomcat

exec gosu $USER "$@"
```
Couldn't create file in the container with tomcat user.
```
bash-4.4# su tomcat
bash-4.4$ ls
LICENSE         bin             logs            work
NOTICE          conf            native-jni-lib
RELEASE-NOTES   include         temp
RUNNING.txt     lib             webapps
bash-4.4$ cd temp/
bash-4.4$ ls
safeToDelete.tmp
bash-4.4$ mkdir test
mkdir: can't create directory 'test': Permission denied
bash-4.4$ ls -la
total 8
drwxr-x---    2 tomcat   tomcat        4096 Mar 21 05:00 .
drwxr-xr-x   23 tomcat   tomcat        4096 Mar 21 05:00 ..
-rw-r-----    1 tomcat   tomcat           0 Nov 27 14:31 safeToDelete.tmp
```

**Comment by MadeInChina** [comment] 2018-03-21 04:38
It's no problem when using tomcat:8.5-jre8-slim

**Comment by tianon** [comment] 2018-04-23 20:33
Just noticed, this is the same issue as https://github.com/docker-library/tomcat/issues/68. :disappointed:

**Comment by tianon** [comment] 2018-04-23 20:36
Posting notes from https://github.com/docker-library/tomcat/issues/118:

> Tomcat should be extracted using  `umask 022`. This will allow users to run tomcat as a different user, maybe multiple different users each with their own `CATALINA_BASE`.

- @jdesmet

> Does simply setting `umask` actually do the trick?  Does upstream have any docs that would make it more clear we need to do this (because we didn't need to in the past), or do we have to link to our own issues about it instead?

- @tianon

**Comment by empinator** [comment] 2018-07-10 11:37
I found one workaround which might help others...

From what I've learned, it's a layer problem, so after I finish all the preparations I simply move the tomcat folder into the user's directory which has been created with the layer, where chown doesn't fail. All you have to do is make sure that CATALINA_HOME is set.

    FROM tomcat:9.0-jre10-slim

    RUN apt-get update \
         && apt-get install --reinstall -y locales \
         && sed -i 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen \
         && locale-gen de_DE.UTF-8

    COPY docker-entrypoint.sh /docker-entrypoint.sh

    # hide ServerInfo in production
    COPY docker/lib/tomcat/ServerInfo.properties /usr/local/tomcat/lib/org/apache/catalina/util/ServerInfo.properties

    COPY target/app /usr/local/tomcat/webapps/ROOT

    # Remove default-apps, create user, move tomcat folder, adjust owner
    RUN rm -rf /usr/local/tomcat/webapps/docs \
        && rm -rf /usr/local/tomcat/webapps/examples \
        && rm -rf /usr/local/tomcat/webapps/host-manager \
        && rm -rf /usr/local/tomcat/webapps/manager \
        && chmod 755 /docker-entrypoint.sh \
        && useradd -ms /bin/bash tcuser \
        && mv /usr/local/tomcat /home/tcuser/ \
        && chown -R tcuser:tcuser /home/tcuser/tomcat

    USER tcuser
    WORKDIR /home/tcuser

    ENV CATALINA_HOME /home/tcuser/tomcat
    ENV LANG de_DE.UTF-8
    ENV LANGUAGE de_DE
    ENV LC_ALL de_DE.UTF-8
    ENV TZ="Europe/Berlin"

    ENTRYPOINT ["/docker-entrypoint.sh", "/home/tcuser/tomcat/bin/catalina.sh", "run"]

    EXPOSE 8080

**Comment by tianon** [comment] 2018-09-06 21:42
I've tried setting `umask 022`, and it didn't do anything meaningful -- I think we need to be more explicit about updating permissions (ie, via `chmod`) for this to work out-of-the-box.

**Comment by tianon** [comment] 2018-09-06 22:01
Got it: https://github.com/docker-library/tomcat/pull/129 :raised_hands:

**Closed** 2018-09-10 21:43 UTC
Labels: Issue

**Comment by PranavBhattarai** [comment] 2020-01-16 03:18
I wonder why this closed when I am still having the same issue.

**Comment by tianon** [comment] 2020-01-16 03:27
@PranavBhattarai probably because we fixed whatever this issue was originally 😉

If you're experiencing something similar, I'd suggest creating a very minimal reproducer and filing a new issue.
