### ISSUE TITLE
Remove src.zip from JDK installation

### ISSUE THREAD

**Issue by ridoo** [docker-library/tomcat#220] opened 2021-02-10 08:54 UTC
After installing the JDK the `src.zip` resides within `${JAVA_HOME}/lib/src.zip`.  Normally, the source are bound to the IDE during development and should not be necessary in Docker images. Removing it would reduce size by ca 60MB. At least for slim versions it would be nice to save some space here.  

I am using `tomcat:9.0-jdk11-openjdk-slim`

**Comment by wglambert** [comment] 2021-02-10 16:20
Duplicate of https://github.com/docker-library/openjdk/issues/282#issuecomment-465373631

**Comment by ridoo** [comment] 2021-02-11 07:14
Thanks @wglambert, docker-library/openjdk#282 raises the same issue. I just want to point out that tomcat is not based on the openjdk image itself, but directly downloads and installs it from github.com/AdoptOpenJDK.

**Comment by tianon** [comment] 2021-02-11 18:11
> Note: The tomcat image is not based on the openjdk image itself, but directly downloads and installs it from github.com/AdoptOpenJDK.

I'm confused by this -- every tag of this image is `FROM` one of the tags of `openjdk`, `adoptopenjdk`, or `amazoncorretto`, depending on the variant?  Do you have a link to a counterexample? :grimacing:

Even more explicitly, here's every `FROM` value in this repository (deduplicated):

```
adoptopenjdk:8-jdk-hotspot
adoptopenjdk:8-jdk-openj9
adoptopenjdk:11-jdk-hotspot
adoptopenjdk:11-jdk-openj9
amazoncorretto:8
amazoncorretto:11
openjdk:8-jdk-buster
openjdk:8-jdk-slim-buster
openjdk:11-jdk-buster
openjdk:11-jdk-slim-buster
openjdk:15-jdk-buster
openjdk:15-jdk-oraclelinux7
openjdk:15-jdk-slim-buster
```

So anywhere we've got `src.zip`, it's coming from our upstream image and removing it here won't actually save any space (due to how Docker's layering works). :confused:

**Comment by ridoo** [comment] 2021-02-12 08:26
@tianon seems to be my fault. I was referring to [what I found on Docker Hub](https://hub.docker.com/layers/tomcat/library/tomcat/jdk11-openjdk-slim/images/sha256-ba841bfe5330060758a7d320f89935defb2880b753a2036b6f623ab5ce78ea18?context=explore).

I should have checked the `Dockerfile`s in the repository :(. Sorry for the confusion.

**Comment by wglambert** [comment] 2021-03-19 17:14
Going to close with what was said in https://github.com/docker-library/openjdk/issues/282#issuecomment-474609791

**Closed by wglambert** 2021-03-19 17:14 UTC
Labels: Request
